version: 2.1

executors:
  gradle_docker:
    docker:
      - image: cimg/openjdk:11.0

commands:
  gradle:
    description: 'Run the provided gradle command'
    parameters:
      args:
        type: string
      when:
        default: "on_success"
        type: enum
        enum: ["on_fail", "on_success", "always"]
    steps:
      - run:
          name: << parameters.args >>
          command: ./gradlew << parameters.args >> --info --max-workers=2 -Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.console=plain
          when: << parameters.when >>
  setup_build_environment:
    description: 'Checkout, restore the cache, and setup docker'
    steps:
      - checkout
      - restore_cache:
          keys: # Use gradle version for cache, so it doesn't download every time
            - v1-dependencies-{{ checksum "./gradle/wrapper/gradle-wrapper.properties" }}
      - setup_remote_docker
  save_populated_cache:
    description: "Save the gradle binary to the cache so it doesn't have to redownload"
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "./gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    executor: gradle_docker
    steps:
      - setup_build_environment
      - gradle:
          args: dockerBuildImages
      - save_populated_cache
  publish:
    executor: gradle_docker
    steps:
      - setup_build_environment
      - gradle:
          args: :tag -Prelease
      - gradle:
          args: dockerPushImages
      - add_ssh_keys:
          fingerprints:
            - 'af:eb:74:05:48:c6:ff:d0:c4:9b:ef:06:6b:b4:fc:55'
      - run: git push origin $(./gradlew -q :printVersion)

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          context: hypertrace-publishing
          requires:
            - build
          filters:
            branches:
              only:
                - master
